# **INFORMACION GENERAL**
## Características del trabajo
Las variables seleccionadas son:

* Semana epidemiológica
* Año epidemiológica, tener en cuenta que la mayoría de filas son del 2022 y la minoría de 2023.
* Departamento
* Municipio
* Sexo
* Edad
* Fecha de inicio de síntomas (modificar datos)
* Fecha de exantema (modificar datos)
* Hospitalización
* Fuente de infección
* Tipo de seguridad social

## Fuentes
Esta base de datos se encontro en Casos positivos de Viruela símica en Colombia en:

*El Instituto Nacional de Salud Publicó el Conjunto de Datos de Viruela Símica en Colombia | Datos Abiertos. (s. f.). https://herramientas.datos.gov.co/noticias/el-instituto-nacional-de-salud-publico-el-conjunto-de-datos-de-viruela-simica-en-colombia*
*texto en cursiva* *texto en cursiva*

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Estadistica J1/Casos_positivos_de_Viruela_s_mica_en_Colombia.csv')

df.loc[:, [ 'Edad','Sexo', 'Fecha de inicio de síntomas', 'Fecha de exantema' ]]

      Edad Sexo Fecha de inicio de síntomas        Fecha de exantema
0       18    M     2022-09-15T00:00:00.000  2022-09-15T00:00:00.000
1       30    M     2022-09-13T00:00:00.000  2022-09-13T00:00:00.000
2       37    M     2022-09-17T00:00:00.000  2022-09-17T00:00:00.000
3       26    M     2022-08-20T00:00:00.000  2022-08-20T00:00:00.000
4       37    M     2022-09-17T00:00:00.000  2022-09-17T00:00:00.000
...    ...  ...                         ...                      ...
4084    20    M     2022-09-01T00:00:00.000  2022-09-08T00:00:00.000
4085    23    M     2023-02-12T00:00:00.000  2023-02-12T00:00:00.000
4086    20    F     2023-02-19T00:00:00.000  2023-02-19T00:00:00.000
4087    33    M     2023-02-13T00:00:00.000  2023-02-13T00:00:00.000
4088    24    M     2023-02-14T00:00:00.000  2023-02-14T00:00:00.000

[4089 rows x 4 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4089 entries, 0 to 4088
Data columns (total 24 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Semana epidemiológica                 4089 non-null   int64
 1   Año epidemiológico                    4089 non-null   int64
 2   Código DIVIPOLA departamento          4089 non-null   int64
 3   Código DIVIPOLA municipio             4089 non-null   int64
 4   Departamento                          4089 non-null   object
 5   Municipio                             4089 non-null   object
 6   Fecha notificación                    4089 non-null   object
 7   Fecha diagnóstico                     4088 non-null   object
 8   Sexo                                  4089 non-null   object
 9   Edad                                  4089 non-null   int64
 10  Unidad de medida                      4089 non-null   int64
 11  Fecha de inicio de síntomas           4089 non-null   object
 12  Fecha de exantema                     4089 non-null   object
 13  Hospitalización                       4089 non-null   int64
 14  Condición final                       4089 non-null   int64
 15  Vínculo epidemiológico                4089 non-null   int64
 16  ¿Viajó?                               4077 non-null   float64
 17  País de viaje                         166 non-null    object
 18  Fuente de infección                   4089 non-null   object
 19  Fecha de terminación del seguimiento  4089 non-null   object
 20  Pertenencia étnica                    4089 non-null   int64
 21  Nombre grupo étnico                   0 non-null      float64
 22  Tipo de seguridad social              4089 non-null   object
 23  Estrato                               4089 non-null   int64
dtypes: float64(2), int64(11), object(11)
memory usage: 766.8+ KB